import { createContext, useContext, useState, type PropsWithChildren } from 'react';

type Language = 'fr' | 'en';

type LanguageContextValue = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'djmanjuke:language';

// Traductions
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.balance': 'Solde',
    'nav.topUp': 'Augmenter mon solde',
    'nav.admin': 'Admin',
    'nav.jukeboxView': 'Vue jukebox',
    'nav.connectedAs': 'Connecté en tant que',
    'nav.login': 'Connexion',
    'nav.logout': 'Déconnexion',
    'nav.editAddress': "Modifier l'adresse",
    'nav.close': 'Fermer',
    'nav.currentAddress': 'Adresse actuelle ou nouvelle',
    'nav.recentAddresses': 'Adresses utilisées récemment',
    'nav.chooseAddress': 'Choisir une adresse mémorisée',
    'nav.saveAddress': "Enregistrer l'adresse",
    'nav.cancel': 'Annuler',
    'nav.sessionExpired': 'Session expirée. Reconnectez-vous pour voir votre solde.',
    'nav.balanceUnavailable': 'Solde indisponible pour le moment.',
    'nav.addressEmpty': "L'adresse ne peut pas être vide.",
    'nav.addressSaveError': "Impossible d'enregistrer cette adresse pour le moment.",
    
    // PlaceJukebox
    'jukebox.nowPlaying': "À l'écoute",
    'jukebox.previous': '◀ Précédente',
    'jukebox.next': 'Suivante ▶',
    'jukebox.search': 'Rechercher une chanson ou un artiste...',
    'jukebox.searchJukebox': 'Rechercher un jukebox...',
    'jukebox.invested': 'Investit',
    'jukebox.jukebox': 'Jukebox',
    'jukebox.refresh': 'Rafraîchir la playlist',
    'jukebox.noResults': 'Aucun résultat pour « {term} »',
    'jukebox.noGolden': 'Aucune chanson Golden disponible pour le moment.',
    'jukebox.emptyQueue': 'La file est vide pour le moment. Rafraîchissez pour charger de nouvelles chansons.',
    'jukebox.loadingJukeboxes': 'Chargement des jukebox...',
    'jukebox.noJukeboxes': 'Aucun jukebox disponible pour le moment.',
    'jukebox.skipNextAdmin': 'Passer à la prochaine chanson (admin)',
    
    // JukeboxCard
    'card.online': 'En ligne',
    'card.offline': 'Hors ligne',
    
    // Register
    'register.title': 'Créer votre jukebox',
    'register.subtitle': 'Définissez un slug unique pour accéder à votre jukebox : /slug.',
    'register.fullName': 'Nom complet',
    'register.email': 'Courriel',
    'register.password': 'Mot de passe',
    'register.jukeboxName': 'Nom du jukebox',
    'register.slug': 'Slug du jukebox (lettres, chiffres, tiret ou souligné)',
    'register.avatar': "Avatar du jukebox (optionnel)",
    'register.avatarFormat': 'JPG, PNG, GIF ou WEBP (max 5MB)',
    'register.planChoice': 'Choix du plan',
    'register.planFree': 'Plan Gratuit',
    'register.planFreeDesc': 'Gestion des chansons et lecture du jukebox. Sans revenus ni investissements.',
    'register.planPro': 'Plan Pro',
    'register.planProDesc': 'Investissements, revenus passifs et priorités. Paiement mensuel de 9,99 $.',
    'register.creating': 'Création en cours...',
    'register.create': 'Créer mon jukebox',
    'register.hasAccount': 'Déjà un compte ?',
    'register.login': 'Se connecter',
    'register.emailTaken': 'Le courriel ou le slug est déjà utilisé.',
    'register.error': "Inscription impossible. Vérifiez les informations fournies.",
    'register.proError': "Votre compte Pro a été créé, mais la redirection vers Stripe a échoué. Vous pourrez activer l'abonnement depuis votre profil.",
    
    // Product/SongCard
    'song.invested': 'Investit',
    'song.standard': 'Standard',
    'song.potentialGain': 'Gain potentiel',
    'song.rank': 'Rang',
    'song.totalBet': 'Total misé',
    'song.investments': 'Investissements',
    'song.activeBudget': 'Budget actif',
    'song.activeInvestors': 'Investisseurs actifs',
    'song.none': 'aucun',
    'song.prioritize': 'Prioriser',
    'song.prioritizeFor': 'Prioriser pour {amount}',
    'song.gainOf': 'Gain de {amount}',
    'song.nowPlaying': 'Lecture en cours',
    'song.priorityHeld': 'Priorité détenue ({amount})',
    'song.cancelPriority': 'Annuler ma priorité',
    'song.stopPreview': "Arrêter l'extrait",
    'song.listenFull': 'Écouter en entier',
    'song.listen15s': 'Écouter 15 s',
    'song.buy1': 'Acheter 1$',
    'song.paidPriorityPrecedence': 'Une priorité payante a pris préséance sur votre priorité gratuite. Vous ne pouvez plus prioriser cette chanson.',
    'song.noInvestors': 'Aucun investisseur pour le moment.',
    'song.total': 'Total',
    'song.remaining': 'Restant',
    'song.passiveShare': 'Part passive',
    'song.additionalInvestors': '+{count} investisseur{plural} supplémentaire{plural}',
    'song.fullscreen': 'Plein écran',
    'song.exitFullscreen': 'Quitter le plein écran',
    'song.play': 'Play',
    'song.pause': 'Pause',
    'song.preview': 'Aperçu',
    
    // Admin Tabs
    'admin.profile': 'Profil',
    'admin.songs': 'Gestion des chansons',
    'admin.investment': 'Investissements',
    'admin.revenue': 'Revenus',
    'admin.stats': 'Statistiques',
    'admin.proRequired': ' (Pro)',
    'admin.proSection': 'Cette section est disponible avec le plan Pro (9,99 $/mois).',
    
    // Profile Tab
    'profile.title': 'Profil du compte',
    'profile.subtitle': 'Gérez les informations de votre compte DJManJuke.com et voyez votre statut d\'abonnement.',
    'profile.basicInfo': 'Informations de base',
    'profile.email': 'Courriel',
    'profile.username': 'Nom d\'utilisateur',
    'profile.jukeboxName': 'Nom du jukebox',
    'profile.slug': 'Slug',
    'profile.subscription': 'Plan d\'abonnement (9,99 $/mois)',
    'profile.currentPlan': 'Plan actuel :',
    'profile.status': 'Statut',
    'profile.active': 'Actif',
    'profile.trial': 'Essai',
    'profile.inactive': 'Inactif',
    'profile.proDescription': 'Le plan Pro (9,99 $/mois) débloque les retraits de gains, les investissements Golden et des outils avancés pour optimiser votre jukebox.',
    'profile.proActive': 'Votre plan Pro (9,99 $/mois) est actif. Vous avez accès aux retraits de vos revenus et aux fonctionnalités avancées.',
    'profile.upgradeError': 'Impossible d\'initialiser l\'abonnement Pro. Réessayez plus tard.',
    'profile.updateError': 'Impossible de mettre à jour votre plan. Réessayez plus tard.',
    'profile.upgrading': 'Mise à niveau en cours...',
    'profile.upgrade': 'Je veux passer au plan Pro',
    'profile.updating': 'Mise à jour en cours...',
    'profile.downgrade': 'Revenir au plan Free',
    'profile.downgradeSuccess1': 'Votre compte est revenu au plan Free.\nL\'abonnement mensuel Stripe lié à ce compte a été annulé.',
    'profile.downgradeSuccess2': 'Votre compte est revenu au plan Free.\nAucun abonnement Stripe actif correspondant n\'a été trouvé.',
    'profile.downgradeSuccess3': 'Votre compte est revenu au plan Free.\nVérifiez votre tableau de bord Stripe pour confirmer l\'annulation.',
    'profile.edit': 'Modifier',
    'profile.cancel': 'Annuler',
    'profile.save': 'Enregistrer',
    'profile.saving': 'Enregistrement...',
    'profile.editInfo': 'Modifier les informations',
    'profile.updateSuccess': 'Profil mis à jour avec succès.',
    'profile.updateConflict': 'Ce {field} est déjà utilisé par un autre compte.',
    'profile.deleteAccount': 'Supprimer mon compte',
    'profile.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer votre compte ? Cette action est irréversible.',
    'profile.deleteConfirmButton': 'Oui, supprimer mon compte',
    'profile.deleting': 'Suppression en cours...',
    'profile.deleteSuccess': 'Votre compte a été supprimé avec succès.',
    'profile.deleteError': 'Impossible de supprimer le compte.',
    'profile.lemonarchProtected': 'Le compte lemonarch ne peut pas être supprimé.',
    'profile.passwordRequired': 'Mot de passe requis',
    'profile.incorrectPassword': 'Mot de passe incorrect',
    
    // Song Manager
    'songs.crossfade': 'Cross-fade',
    'songs.crossfadeDesc': 'Transitions fluides entre les chansons (plan Pro uniquement)',
    'songs.crossfadeEnabled': 'Cross-fade activé',
    'songs.crossfadeDisabled': 'Cross-fade désactivé',
    'songs.editSong': 'Modifier la chanson',
    'songs.addSong': 'Ajouter une chanson',
    'songs.formDesc': 'Les fichiers audio sont obligatoires lors de la création. En modification, laissez vide pour conserver les médias actuels.',
    'songs.title': 'Titre',
    'songs.artist': 'Artiste',
    'songs.order': 'Ordre (optionnel)',
    'songs.audioFile': 'Fichier audio/vidéo',
    'songs.audioFileEdit': 'Fichier audio/vidéo (laisser vide pour conserver)',
    'songs.audioFileRequired': 'Fichier audio/vidéo (obligatoire)',
    'songs.imageFile': 'Image (optionnel)',
    'songs.acceptedFormats': 'Formats acceptés: .mp3, .mp4, .wav, .m4a, etc.',
    'songs.genrePrimary': 'Genre principal (optionnel)',
    'songs.genreSecondary': 'Genre secondaire (optionnel)',
    'songs.genreTertiary': 'Genre tertiaire (optionnel)',
    'songs.selectGenre': 'Sélectionner un genre',
    'songs.recordedAt': 'Date d\'enregistrement (optionnel)',
    'songs.saving': 'Enregistrement...',
    'songs.update': 'Mettre à jour',
    'songs.create': 'Créer',
    'songs.cancel': 'Annuler',
    'songs.mySongs': 'Vos chansons',
    'songs.search': 'Rechercher une chanson...',
    'songs.refresh': 'Rafraîchir',
    'songs.tableTitle': 'Titre',
    'songs.tableArtist': 'Artiste',
    'songs.tableGenres': 'Genres',
    'songs.tableDate': 'Date',
    'songs.tableOrder': 'Ordre',
    'songs.tableFile': 'Fichier',
    'songs.tableActions': 'Actions',
    'songs.modify': 'Modifier',
    'songs.delete': 'Supprimer',
    'songs.noResults': 'Aucun résultat pour « {term} ».',
    'songs.noSongs': 'Aucune chanson pour le moment.',
    'songs.platformSongs': 'Chansons de la plateforme',
    'songs.searchCatalog': 'Rechercher dans le catalogue...',
    'songs.catalogDesc': 'Sélectionnez les titres de la plateforme que vous souhaitez rendre disponibles dans votre jukebox.',
    'songs.tableStatus': 'Statut',
    'songs.inJukebox': 'Dans votre jukebox',
    'songs.available': 'Disponible',
    'songs.remove': 'Retirer',
    'songs.add': 'Ajouter',
    'songs.noCatalogResults': 'Aucun résultat pour « {term} ».',
    'songs.noCatalog': 'Aucun titre disponible dans le catalogue.',
    'songs.loadError': 'Impossible de charger vos chansons.',
    'songs.catalogLoadError': 'Impossible de charger les chansons de la plateforme.',
    'songs.deleteError': 'Suppression impossible.',
    'songs.deleteSuccess': '« {title} » a été supprimée de votre catalogue.',
    'songs.updateError': 'Mise à jour impossible. Vérifiez les informations.',
    'songs.createError': 'Création impossible. Vérifiez les informations.',
    'songs.updateSuccess': 'Chanson mise à jour.',
    'songs.createSuccess': 'Chanson créée.',
    'songs.attachSuccess': 'La chanson a été ajoutée à votre jukebox.',
    'songs.attachError': 'Ajout impossible. Réessayez plus tard.',
    'songs.detachSuccess': 'La chanson a été retirée de votre jukebox.',
    'songs.detachError': 'Retrait impossible. Réessayez plus tard.',
    
    // Investment Manager
    'investment.title': 'Investir dans vos chansons et le catalogue global',
    'investment.subtitle': 'Ajoutez un budget pour mettre vos chansons en avant, ou investissez dans le catalogue de la plateforme. Chaque lecture consomme un montant équivalent au prix de priorité courant. Une fois le budget épuisé, vous recevrez 20 % des revenus futurs générés par ces chansons.',
    'investment.mySongs': 'Vos chansons',
    'investment.platformCatalog': 'Catalogue plateforme & autres créateurs',
    'investment.amountToInvest': 'Montant à investir',
    'investment.processing': 'Traitement...',
    'investment.invest': 'Investir',
    'investment.activeInvestments': 'Investissements actifs',
    'investment.budgetRemaining': 'Budget restant',
    'investment.passiveInvestors': 'Investisseurs passifs (20 % partagé)',
    'investment.noInvestments': 'Aucun investissement pour l\'instant.',
    'investment.owner': 'Propriétaire',
    'investment.inJukebox': 'Présente dans votre jukebox',
    'investment.notInJukebox': 'Pas encore ajoutée à votre jukebox',
    'investment.order': 'Ordre',
    'investment.passiveSummary': 'Résumé de vos parts passives',
    'investment.totalInvested': 'Total investi',
    'investment.passiveShare': 'Part passive',
    'investment.passiveYes': 'oui',
    'investment.passiveNo': 'non',
    'investment.noPassiveInvestments': 'Aucun investissement enregistré.',
    'investment.passiveShareCount': 'Vous partagez actuellement 20 % des revenus de {count} chanson(s).',
    'investment.noSongs': 'Vous n\'avez pas encore ajouté de chanson.',
    'investment.noOtherSongs': 'Aucun autre titre disponible pour le moment. Ajoutez des chansons via la bibliothèque pour élargir vos possibilités d\'investissement.',
    'investment.loadError': 'Impossible de charger les données d\'investissement.',
    'investment.amountRequired': 'Veuillez saisir un montant.',
    'investment.invalidAmount': 'Montant invalide.',
    'investment.saveError': 'Impossible d\'enregistrer l\'investissement.',
    'investment.saveSuccess': 'Investissement enregistré.',
    
    // Revenue Dashboard
    'revenue.title': 'Revenus',
    'revenue.subtitle': 'Ce tableau récapitule vos gains selon la répartition à 5 × 20 % : propriétaire de la chanson, investisseurs Golden, propriétaire du jukebox, payeurs et plateforme.',
    'revenue.refreshing': 'Actualisation...',
    'revenue.refresh': 'Actualiser',
    'revenue.availableBalance': 'Solde disponible',
    'revenue.minWithdrawal': 'Minimum de retrait',
    'revenue.pending': 'En attente',
    'revenue.stripeTransferable': 'Limite transférable Stripe',
    'revenue.stripeBalance': 'limité par le solde Stripe',
    'revenue.amountToWithdraw': 'Montant à retirer (optionnel)',
    'revenue.withdrawAll': 'Tout retirer',
    'revenue.minimum': 'Minimum',
    'revenue.activateStripe': 'Activer mon compte Stripe',
    'revenue.connectingStripe': 'Redirection vers Stripe...',
    'revenue.withdrawing': 'Retrait en cours...',
    'revenue.withdraw': 'Retirer mes gains',
    'revenue.totalPaid': 'Payé au total',
    'revenue.totalPaidDesc': 'Historique cumulé de vos retraits confirmés.',
    'revenue.lifetimeGross': 'Gains cumulés',
    'revenue.lifetimeGrossDesc': 'Montant total gagné depuis vos débuts sur la plateforme.',
    'revenue.songOwner': 'Propriétaire de la chanson',
    'revenue.songOwnerDesc': '20 % sur chaque lecture ou priorité de vos propres chansons.',
    'revenue.investor': 'Investisseur Golden',
    'revenue.investorDesc': 'Part passive (20 % partagé) sur les Golden Songs où vous avez investi.',
    'revenue.jukeboxOwner': 'Propriétaire du jukebox',
    'revenue.jukeboxOwnerDesc': '20 % attribué à votre jukebox.',
    'revenue.payer': 'Réenchérissements',
    'revenue.payerDesc': '20 % lorsque vous avez payé pour prioriser une chanson. Sur les Golden Songs, ce montant vous revient grâce aux mises payées par les autres utilisateurs (pas vos investissements).',
    'revenue.platform': 'Plateforme',
    'revenue.platformDesc': 'Part de la plateforme associée à votre compte.',
    'revenue.balanceMovements': 'Mouvements du solde',
    'revenue.balanceMovementsDesc': 'Recharges, achats/priorités payés avec votre solde interne et retraits Stripe vers votre compte bancaire.',
    'revenue.tableDate': 'Date',
    'revenue.tableAmount': 'Montant',
    'revenue.tableType': 'Type',
    'revenue.tableStatus': 'Statut',
    'revenue.tableStripeId': 'Stripe ID',
    'revenue.tableConfirmation': 'Confirmation',
    'revenue.typeTopUp': 'Recharge de solde (carte/Stripe)',
    'revenue.typePayout': 'Retrait Stripe vers votre compte',
    'revenue.typeInternal': 'Achat/priorité payé avec le solde',
    'revenue.statusPaid': 'Payé',
    'revenue.statusProcessing': 'En cours',
    'revenue.statusPending': 'En attente',
    'revenue.statusFailed': 'Échoué',
    'revenue.payoutDesc': 'Décaissement Stripe vers votre compte bancaire.',
    'revenue.internalDebitDesc': 'Débit de votre solde interne pour un achat ou une priorité.',
    'revenue.topUpDesc': 'Crédit de votre solde interne suite à une recharge.',
    'revenue.noPayouts': 'Aucun retrait pour le moment. Dès que vous lancez un transfert, il apparaîtra ici.',
    'revenue.loadError': 'Impossible de charger vos revenus.',
    'revenue.withdrawError': 'Impossible d\'initier le retrait.',
    'revenue.withdrawSuccess1': 'Retrait complété avec succès.',
    'revenue.withdrawSuccess2': 'Retrait en cours de traitement. Vous recevrez une confirmation Stripe sous peu.',
    'revenue.stripeError': 'Lien Stripe invalide. Réessayez plus tard.',
    'revenue.stripeContactError': 'Impossible de contacter Stripe. Réessayez plus tard.',
    'revenue.proRequired': 'Passez au plan Pro pour débloquer les retraits de vos revenus.',
    'revenue.connectStripe': 'Connectez votre compte Stripe Connect pour activer les retraits.',
    'revenue.stripeVerifying': 'Votre compte Stripe est en cours de vérification. Stripe vous avertira dès que les retraits seront activés.',
    'revenue.minAmountRequired': 'Le montant à retirer doit être au moins de {amount}.',
    'revenue.amountExceeds': 'Le montant demandé dépasse votre solde disponible ({amount}).',
    'revenue.withdrawInfo': 'Transférez une partie ou la totalité de vos revenus disponibles vers votre compte bancaire via Stripe Connect.',
    
    // Stats Dashboard
    'stats.title': 'Statistiques',
    'stats.subtitle': 'Visualisez où vos chansons et vos jukebox performent le mieux pour orienter vos décisions marketing.',
    'stats.refreshing': 'Actualisation...',
    'stats.refresh': 'Actualiser',
    'stats.topSongs': 'Vos chansons les plus jouées',
    'stats.topSongsDesc': 'Classement basé sur le nombre total de lectures, tous jukebox confondus.',
    'stats.topJukeboxes': 'Vos jukebox les plus actifs',
    'stats.topJukeboxesDesc': 'Classement basé sur le nombre total de lectures des chansons dans chacun de vos jukebox.',
    'stats.plays': 'lectures',
    'stats.bet': 'misés',
    'stats.unknownJukebox': 'jukebox inconnu',
    'stats.noLocationInfo': 'Aucune information de lieu disponible pour cette chanson.',
    'stats.noSongPlays': 'Aucune lecture enregistrée pour vos chansons pour le moment.',
    'stats.noJukeboxName': 'Jukebox sans nom',
    'stats.noJukeboxSongs': 'Aucune chanson jouée sur ce jukebox pour le moment.',
    'stats.noActiveJukeboxes': 'Aucun jukebox actif pour le moment. Dès que vos jukebox diffuseront des chansons, les statistiques apparaîtront ici.',
    'stats.footer': 'Les nombres de lectures sont basés sur les lectures payantes effectuées via les jukebox. Les montants correspondent aux sommes misées pour prioriser ou jouer les chansons.',
    'stats.loadError': 'Impossible de charger les statistiques pour le moment.',
    
    // Playback Mode
    'playback.public': 'Public',
    'playback.private': 'Privé',
    'playback.publicTitle': 'Mode public (haut-parleurs)',
    'playback.privateTitle': 'Mode privé',
    'playback.publicActivated': 'Mode public activé',
    'playback.privateActivated': 'Mode privé activé',
    'playback.modeError': 'Erreur lors du changement de mode',
    
    // Toast Messages
    'toast.priorityFreeApplied': 'Priorité gratuite appliquée (plan Pro)',
    'toast.priorityCanceled': 'Ta priorité gratuite a été annulée.',
    'toast.priorityCanceledBalance': 'Ta priorité a été annulée et ton solde a été libéré.',
    'toast.previewFailed': 'Impossible de vérifier l\'effet de cette priorité pour le moment. Réessaie plus tard.',
    'toast.buyTrackFailed': 'Impossible d\'acheter cette chanson pour le moment. Réessaie plus tard.',
    'toast.cancelPriorityFailed': 'Impossible d\'annuler la priorité pour le moment. Réessaie plus tard.',
    'toast.loginRequired': 'Connecte-toi pour annuler ta priorité.',
    'toast.purchaseConfirmed': 'Achat confirmé ! Le téléchargement va démarrer. Merci pour votre soutien.',
    'toast.downloadFailed': 'Le débit a été confirmé, mais le téléchargement a échoué.',
    'toast.jukeboxListError': 'Impossible de charger la liste des jukebox',
    'toast.priorityFromBalanceError': 'Impossible d\'utiliser tes gains pour cette priorité pour le moment.',
    
    // Common
    'common.loading': 'Chargement...',
  },
  en: {
    // Navigation
    'nav.balance': 'Balance',
    'nav.topUp': 'Top up my balance',
    'nav.admin': 'Admin',
    'nav.jukeboxView': 'Jukebox view',
    'nav.connectedAs': 'Connected as',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.editAddress': 'Edit address',
    'nav.close': 'Close',
    'nav.currentAddress': 'Current or new address',
    'nav.recentAddresses': 'Recently used addresses',
    'nav.chooseAddress': 'Choose a saved address',
    'nav.saveAddress': 'Save address',
    'nav.cancel': 'Cancel',
    'nav.sessionExpired': 'Session expired. Please reconnect to view your balance.',
    'nav.balanceUnavailable': 'Balance unavailable at the moment.',
    'nav.addressEmpty': 'Address cannot be empty.',
    'nav.addressSaveError': 'Unable to save this address at the moment.',
    
    // PlaceJukebox
    'jukebox.nowPlaying': 'Now Playing',
    'jukebox.previous': '◀ Previous',
    'jukebox.next': 'Next ▶',
    'jukebox.search': 'Search for a song or artist...',
    'jukebox.searchJukebox': 'Search for a jukebox...',
    'jukebox.invested': 'Invested',
    'jukebox.jukebox': 'Jukebox',
    'jukebox.refresh': 'Refresh playlist',
    'jukebox.noResults': 'No results for "{term}"',
    'jukebox.noGolden': 'No Golden songs available at the moment.',
    'jukebox.emptyQueue': 'The queue is empty. Refresh to load new songs.',
    'jukebox.loadingJukeboxes': 'Loading jukeboxes...',
    'jukebox.noJukeboxes': 'No jukeboxes available at the moment.',
    'jukebox.skipNextAdmin': 'Skip to next song (admin)',
    
    // JukeboxCard
    'card.online': 'Online',
    'card.offline': 'Offline',
    
    // Register
    'register.title': 'Create your jukebox',
    'register.subtitle': 'Set a unique slug to access your jukebox: /slug.',
    'register.fullName': 'Full name',
    'register.email': 'Email',
    'register.password': 'Password',
    'register.jukeboxName': 'Jukebox name',
    'register.slug': 'Jukebox slug (letters, numbers, dash or underscore)',
    'register.avatar': 'Jukebox avatar (optional)',
    'register.avatarFormat': 'JPG, PNG, GIF or WEBP (max 5MB)',
    'register.planChoice': 'Plan selection',
    'register.planFree': 'Free Plan',
    'register.planFreeDesc': 'Song management and jukebox playback. No revenue or investments.',
    'register.planPro': 'Pro Plan',
    'register.planProDesc': 'Investments, passive revenue and priorities. Monthly payment of $9.99.',
    'register.creating': 'Creating...',
    'register.create': 'Create my jukebox',
    'register.hasAccount': 'Already have an account?',
    'register.login': 'Log in',
    'register.emailTaken': 'Email or slug is already taken.',
    'register.error': 'Registration failed. Please check the information provided.',
    'register.proError': 'Your Pro account has been created, but the redirect to Stripe failed. You can activate the subscription from your profile.',
    
    // Product/SongCard
    'song.invested': 'Invested',
    'song.standard': 'Standard',
    'song.potentialGain': 'Potential gain',
    'song.rank': 'Rank',
    'song.totalBet': 'Total bet',
    'song.investments': 'Investments',
    'song.activeBudget': 'Active budget',
    'song.activeInvestors': 'Active investors',
    'song.none': 'none',
    'song.prioritize': 'Prioritize',
    'song.prioritizeFor': 'Prioritize for {amount}',
    'song.gainOf': 'Gain of {amount}',
    'song.nowPlaying': 'Now playing',
    'song.priorityHeld': 'Priority held ({amount})',
    'song.cancelPriority': 'Cancel my priority',
    'song.stopPreview': 'Stop preview',
    'song.listenFull': 'Listen in full',
    'song.listen15s': 'Listen 15s',
    'song.buy1': 'Buy $1',
    'song.paidPriorityPrecedence': 'A paid priority has taken precedence over your free priority. You can no longer prioritize this song.',
    'song.noInvestors': 'No investors at the moment.',
    'song.total': 'Total',
    'song.remaining': 'Remaining',
    'song.passiveShare': 'Passive share',
    'song.additionalInvestors': '+{count} additional investor{plural}',
    'song.fullscreen': 'Fullscreen',
    'song.exitFullscreen': 'Exit fullscreen',
    'song.play': 'Play',
    'song.pause': 'Pause',
    'song.preview': 'Preview',
    
    // Admin Tabs
    'admin.profile': 'Profile',
    'admin.songs': 'Song Management',
    'admin.investment': 'Investments',
    'admin.revenue': 'Revenue',
    'admin.stats': 'Statistics',
    'admin.proRequired': ' (Pro)',
    'admin.proSection': 'This section is available with the Pro plan ($9.99/month).',
    
    // Profile Tab
    'profile.title': 'Account Profile',
    'profile.subtitle': 'Manage your DJManJuke.com account information and view your subscription status.',
    'profile.basicInfo': 'Basic Information',
    'profile.email': 'Email',
    'profile.username': 'Username',
    'profile.jukeboxName': 'Jukebox Name',
    'profile.slug': 'Slug',
    'profile.subscription': 'Subscription Plan ($9.99/month)',
    'profile.currentPlan': 'Current plan:',
    'profile.status': 'Status',
    'profile.active': 'Active',
    'profile.trial': 'Trial',
    'profile.inactive': 'Inactive',
    'profile.proDescription': 'The Pro plan ($9.99/month) unlocks revenue withdrawals, Golden investments, and advanced tools to optimize your jukebox.',
    'profile.proActive': 'Your Pro plan ($9.99/month) is active. You have access to revenue withdrawals and advanced features.',
    'profile.upgradeError': 'Unable to initialize Pro subscription. Please try again later.',
    'profile.updateError': 'Unable to update your plan. Please try again later.',
    'profile.upgrading': 'Upgrading...',
    'profile.upgrade': 'I want to upgrade to Pro plan',
    'profile.updating': 'Updating...',
    'profile.downgrade': 'Return to Free plan',
    'profile.downgradeSuccess1': 'Your account has returned to the Free plan.\nThe monthly Stripe subscription linked to this account has been canceled.',
    'profile.downgradeSuccess2': 'Your account has returned to the Free plan.\nNo matching active Stripe subscription was found.',
    'profile.downgradeSuccess3': 'Your account has returned to the Free plan.\nCheck your Stripe dashboard to confirm cancellation.',
    'profile.edit': 'Edit',
    'profile.cancel': 'Cancel',
    'profile.save': 'Save',
    'profile.saving': 'Saving...',
    'profile.editInfo': 'Edit Information',
    'profile.updateSuccess': 'Profile updated successfully.',
    'profile.updateConflict': 'This {field} is already used by another account.',
    'profile.deleteAccount': 'Delete My Account',
    'profile.deleteConfirm': 'Are you sure you want to delete your account? This action is irreversible.',
    'profile.deleteConfirmButton': 'Yes, delete my account',
    'profile.deleting': 'Deleting...',
    'profile.deleteSuccess': 'Your account has been successfully deleted.',
    'profile.deleteError': 'Unable to delete account.',
    'profile.lemonarchProtected': 'The lemonarch account cannot be deleted.',
    'profile.passwordRequired': 'Password required',
    'profile.incorrectPassword': 'Incorrect password',
    
    // Song Manager
    'songs.crossfade': 'Cross-fade',
    'songs.crossfadeDesc': 'Smooth transitions between songs (Pro plan only)',
    'songs.crossfadeEnabled': 'Cross-fade enabled',
    'songs.crossfadeDisabled': 'Cross-fade disabled',
    'songs.editSong': 'Edit Song',
    'songs.addSong': 'Add Song',
    'songs.formDesc': 'Audio files are required when creating. When editing, leave empty to keep current media.',
    'songs.title': 'Title',
    'songs.artist': 'Artist',
    'songs.order': 'Order (optional)',
    'songs.audioFile': 'Audio/Video File',
    'songs.audioFileEdit': 'Audio/Video File (leave empty to keep)',
    'songs.audioFileRequired': 'Audio/Video File (required)',
    'songs.imageFile': 'Image (optional)',
    'songs.acceptedFormats': 'Accepted formats: .mp3, .mp4, .wav, .m4a, etc.',
    'songs.genrePrimary': 'Primary Genre (optional)',
    'songs.genreSecondary': 'Secondary Genre (optional)',
    'songs.genreTertiary': 'Tertiary Genre (optional)',
    'songs.selectGenre': 'Select a genre',
    'songs.recordedAt': 'Recording Date (optional)',
    'songs.saving': 'Saving...',
    'songs.update': 'Update',
    'songs.create': 'Create',
    'songs.cancel': 'Cancel',
    'songs.mySongs': 'Your Songs',
    'songs.search': 'Search for a song...',
    'songs.refresh': 'Refresh',
    'songs.tableTitle': 'Title',
    'songs.tableArtist': 'Artist',
    'songs.tableGenres': 'Genres',
    'songs.tableDate': 'Date',
    'songs.tableOrder': 'Order',
    'songs.tableFile': 'File',
    'songs.tableActions': 'Actions',
    'songs.modify': 'Modify',
    'songs.delete': 'Delete',
    'songs.noResults': 'No results for "{term}".',
    'songs.noSongs': 'No songs at the moment.',
    'songs.platformSongs': 'Platform Songs',
    'songs.searchCatalog': 'Search catalog...',
    'songs.catalogDesc': 'Select platform titles you want to make available in your jukebox.',
    'songs.tableStatus': 'Status',
    'songs.inJukebox': 'In your jukebox',
    'songs.available': 'Available',
    'songs.remove': 'Remove',
    'songs.add': 'Add',
    'songs.noCatalogResults': 'No results for "{term}".',
    'songs.noCatalog': 'No titles available in the catalog.',
    'songs.loadError': 'Unable to load your songs.',
    'songs.catalogLoadError': 'Unable to load platform songs.',
    'songs.deleteError': 'Deletion failed.',
    'songs.deleteSuccess': '"{title}" has been removed from your catalog.',
    'songs.updateError': 'Update failed. Please check the information.',
    'songs.createError': 'Creation failed. Please check the information.',
    'songs.updateSuccess': 'Song updated.',
    'songs.createSuccess': 'Song created.',
    'songs.attachSuccess': 'The song has been added to your jukebox.',
    'songs.attachError': 'Addition failed. Please try again later.',
    'songs.detachSuccess': 'The song has been removed from your jukebox.',
    'songs.detachError': 'Removal failed. Please try again later.',
    
    // Investment Manager
    'investment.title': 'Invest in Your Songs and Global Catalog',
    'investment.subtitle': 'Add a budget to promote your songs, or invest in the platform catalog. Each play consumes an amount equivalent to the current priority price. Once the budget is exhausted, you will receive 20% of future revenue generated by these songs.',
    'investment.mySongs': 'Your Songs',
    'investment.platformCatalog': 'Platform Catalog & Other Creators',
    'investment.amountToInvest': 'Amount to Invest',
    'investment.processing': 'Processing...',
    'investment.invest': 'Invest',
    'investment.activeInvestments': 'Active investments',
    'investment.budgetRemaining': 'Budget remaining',
    'investment.passiveInvestors': 'Passive investors (20% shared)',
    'investment.noInvestments': 'No investments at the moment.',
    'investment.owner': 'Owner',
    'investment.inJukebox': 'Present in your jukebox',
    'investment.notInJukebox': 'Not yet added to your jukebox',
    'investment.order': 'Order',
    'investment.passiveSummary': 'Summary of Your Passive Shares',
    'investment.totalInvested': 'Total invested',
    'investment.passiveShare': 'Passive share',
    'investment.passiveYes': 'yes',
    'investment.passiveNo': 'no',
    'investment.noPassiveInvestments': 'No investments recorded.',
    'investment.passiveShareCount': 'You currently share 20% of revenue from {count} song(s).',
    'investment.noSongs': 'You haven\'t added any songs yet.',
    'investment.noOtherSongs': 'No other titles available at the moment. Add songs via the library to expand your investment opportunities.',
    'investment.loadError': 'Unable to load investment data.',
    'investment.amountRequired': 'Please enter an amount.',
    'investment.invalidAmount': 'Invalid amount.',
    'investment.saveError': 'Unable to save investment.',
    'investment.saveSuccess': 'Investment recorded.',
    
    // Revenue Dashboard
    'revenue.title': 'Revenue',
    'revenue.subtitle': 'This dashboard summarizes your earnings according to the 5 × 20% split: song owner, Golden investors, jukebox owner, payers, and platform.',
    'revenue.refreshing': 'Refreshing...',
    'revenue.refresh': 'Refresh',
    'revenue.availableBalance': 'Available Balance',
    'revenue.minWithdrawal': 'Minimum withdrawal',
    'revenue.pending': 'Pending',
    'revenue.stripeTransferable': 'Stripe Transferable Limit',
    'revenue.stripeBalance': 'limited by Stripe balance',
    'revenue.amountToWithdraw': 'Amount to withdraw (optional)',
    'revenue.withdrawAll': 'Withdraw All',
    'revenue.minimum': 'Minimum',
    'revenue.activateStripe': 'Activate My Stripe Account',
    'revenue.connectingStripe': 'Redirecting to Stripe...',
    'revenue.withdrawing': 'Withdrawing...',
    'revenue.withdraw': 'Withdraw My Earnings',
    'revenue.totalPaid': 'Total Paid',
    'revenue.totalPaidDesc': 'Cumulative history of your confirmed withdrawals.',
    'revenue.lifetimeGross': 'Lifetime Earnings',
    'revenue.lifetimeGrossDesc': 'Total amount earned since you started on the platform.',
    'revenue.songOwner': 'Song Owner',
    'revenue.songOwnerDesc': '20% on each play or priority of your own songs.',
    'revenue.investor': 'Golden Investor',
    'revenue.investorDesc': 'Passive share (20% shared) on Golden Songs where you invested.',
    'revenue.jukeboxOwner': 'Jukebox Owner',
    'revenue.jukeboxOwnerDesc': '20% attributed to your jukebox.',
    'revenue.payer': 'Rebids',
    'revenue.payerDesc': '20% when you paid to prioritize a song. On Golden Songs, this amount comes back to you through bids paid by other users (not your investments).',
    'revenue.platform': 'Platform',
    'revenue.platformDesc': 'Platform share associated with your account.',
    'revenue.balanceMovements': 'Balance Movements',
    'revenue.balanceMovementsDesc': 'Top-ups, purchases/priorities paid with your internal balance and Stripe withdrawals to your bank account.',
    'revenue.tableDate': 'Date',
    'revenue.tableAmount': 'Amount',
    'revenue.tableType': 'Type',
    'revenue.tableStatus': 'Status',
    'revenue.tableStripeId': 'Stripe ID',
    'revenue.tableConfirmation': 'Confirmation',
    'revenue.typeTopUp': 'Balance Top-up (card/Stripe)',
    'revenue.typePayout': 'Stripe Withdrawal to Your Account',
    'revenue.typeInternal': 'Purchase/priority paid with balance',
    'revenue.statusPaid': 'Paid',
    'revenue.statusProcessing': 'Processing',
    'revenue.statusPending': 'Pending',
    'revenue.statusFailed': 'Failed',
    'revenue.payoutDesc': 'Stripe disbursement to your bank account.',
    'revenue.internalDebitDesc': 'Debit from your internal balance for a purchase or priority.',
    'revenue.topUpDesc': 'Credit to your internal balance following a top-up.',
    'revenue.noPayouts': 'No withdrawals at the moment. As soon as you initiate a transfer, it will appear here.',
    'revenue.loadError': 'Unable to load your revenue.',
    'revenue.withdrawError': 'Unable to initiate withdrawal.',
    'revenue.withdrawSuccess1': 'Withdrawal completed successfully.',
    'revenue.withdrawSuccess2': 'Withdrawal being processed. You will receive a Stripe confirmation shortly.',
    'revenue.stripeError': 'Invalid Stripe link. Please try again later.',
    'revenue.stripeContactError': 'Unable to contact Stripe. Please try again later.',
    'revenue.proRequired': 'Upgrade to Pro plan to unlock revenue withdrawals.',
    'revenue.connectStripe': 'Connect your Stripe Connect account to enable withdrawals.',
    'revenue.stripeVerifying': 'Your Stripe account is being verified. Stripe will notify you once withdrawals are enabled.',
    'revenue.minAmountRequired': 'The withdrawal amount must be at least {amount}.',
    'revenue.amountExceeds': 'The requested amount exceeds your available balance ({amount}).',
    'revenue.withdrawInfo': 'Transfer part or all of your available revenue to your bank account via Stripe Connect.',
    
    // Stats Dashboard
    'stats.title': 'Statistics',
    'stats.subtitle': 'Visualize where your songs and jukeboxes perform best to guide your marketing decisions.',
    'stats.refreshing': 'Refreshing...',
    'stats.refresh': 'Refresh',
    'stats.topSongs': 'Your Most Played Songs',
    'stats.topSongsDesc': 'Ranking based on total number of plays across all jukeboxes.',
    'stats.topJukeboxes': 'Your Most Active Jukeboxes',
    'stats.topJukeboxesDesc': 'Ranking based on total number of song plays in each of your jukeboxes.',
    'stats.plays': 'plays',
    'stats.bet': 'bet',
    'stats.unknownJukebox': 'unknown jukebox',
    'stats.noLocationInfo': 'No location information available for this song.',
    'stats.noSongPlays': 'No plays recorded for your songs at the moment.',
    'stats.noJukeboxName': 'Unnamed Jukebox',
    'stats.noJukeboxSongs': 'No songs played on this jukebox at the moment.',
    'stats.noActiveJukeboxes': 'No active jukeboxes at the moment. As soon as your jukeboxes start playing songs, statistics will appear here.',
    'stats.footer': 'Play counts are based on paid plays made via jukeboxes. Amounts correspond to sums bet to prioritize or play songs.',
    'stats.loadError': 'Unable to load statistics at the moment.',
    
    // Playback Mode
    'playback.public': 'Public',
    'playback.private': 'Private',
    'playback.publicTitle': 'Public Mode (speakers)',
    'playback.privateTitle': 'Private Mode',
    'playback.publicActivated': 'Public mode activated',
    'playback.privateActivated': 'Private mode activated',
    'playback.modeError': 'Error changing mode',
    
    // Toast Messages
    'toast.priorityFreeApplied': 'Free priority applied (Pro plan)',
    'toast.priorityCanceled': 'Your free priority has been canceled.',
    'toast.priorityCanceledBalance': 'Your priority has been canceled and your balance has been released.',
    'toast.previewFailed': 'Unable to check the effect of this priority at the moment. Please try again later.',
    'toast.buyTrackFailed': 'Unable to purchase this track at the moment. Please try again later.',
    'toast.cancelPriorityFailed': 'Unable to cancel priority at the moment. Please try again later.',
    'toast.loginRequired': 'Log in to cancel your priority.',
    'toast.purchaseConfirmed': 'Purchase confirmed! Download will start. Thank you for your support.',
    'toast.downloadFailed': 'Debit was confirmed, but download failed.',
    'toast.jukeboxListError': 'Unable to load jukebox list',
    'toast.priorityFromBalanceError': 'Unable to use your earnings for this priority at the moment.',
    
    // Common
    'common.loading': 'Loading...',
  },
};

const getStoredLanguage = (): Language => {
  const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return (stored === 'fr' || stored === 'en') ? stored : 'fr';
};

const persistLanguage = (language: Language) => {
  localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
};

export const LanguageProvider = ({ children }: PropsWithChildren) => {
  const [language, setLanguageState] = useState<Language>(getStoredLanguage);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    persistLanguage(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language]?.[key];
    if (!translation) {
      console.warn(`Translation missing for key: ${key}`);
      return key;
    }
    // Remplacer les placeholders {key} par les valeurs
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translation = translation.replace(`{${paramKey}}`, String(paramValue));
      });
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

